# Travis CI
dist: xenial
language: python

python:
  - "3.7"

cache:
  - pip

install:
  - pip install -r scripts/requirements.txt
  - pip install -r scripts/dev_requirements.txt
  - python setup.py develop

services:
  - redis-server
  - postgresql

before-script:
  - psql -c 'CREATE DATABASE dtftest;' -U postgres
  - psql -c "CREATE USER dtftest with PASSWORD 'dtftest';" -U postgres
  - psql -c 'ALTER USER dtftest CREATEDB CREATEROLE LOGIN;' - U postgres

script:
  - pushd demo
  - pytest demo --cov=demo --cov=django_taskflow --cov-report term-missing

after_success:
  - coveralls
